package component:dyna;

world dynamic-dispatch {
    import dynamic-component;
}
    
interface dynamic-component {
    resource engine {
        constructor();
        load-component: func(bytes: list<u8>) -> result<component, load-error>;
    }

    resource component {
        call: func(name: string, params: list<val>) -> list<val>;
    }

    variant val {
        str(string)
    }

    variant load-error {
        invalid-bytes(string)
    }
}
