package component:dyna;

world dynamic-dispatch {
    import dynamic-component;
}
    
interface dynamic-component {
    load-component: func(path: string) -> component;

    resource component {
        call: func(name: string, params: list<val>) -> list<val>;
    }

    variant val {
        str(string)
    }
}
